//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoordinateTrackerAndClicker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoordinateTrackerAndClicker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави като ново действие.
        /// </summary>
        internal static string btnAddAction {
            get {
                return ResourceManager.GetString("btnAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай ново макро.
        /// </summary>
        internal static string btnCreateMacro {
            get {
                return ResourceManager.GetString("btnCreateMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпълни.
        /// </summary>
        internal static string btnExecuteMacro {
            get {
                return ResourceManager.GetString("btnExecuteMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        internal static string btnMacroDelete {
            get {
                return ResourceManager.GetString("btnMacroDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        internal static string btnMacroSave {
            get {
                return ResourceManager.GetString("btnMacroSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локация.
        /// </summary>
        internal static string btnNewSavePath {
            get {
                return ResourceManager.GetString("btnNewSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт запис.
        /// </summary>
        internal static string btnStartRecording {
            get {
                return ResourceManager.GetString("btnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спри.
        /// </summary>
        internal static string btnStopMacro {
            get {
                return ResourceManager.GetString("btnStopMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп запис.
        /// </summary>
        internal static string btnStopRecording {
            get {
                return ResourceManager.GetString("btnStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуснати.
        /// </summary>
        internal static string BtnSwitchModalAlert {
            get {
                return ResourceManager.GetString("BtnSwitchModalAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светла.
        /// </summary>
        internal static string btnSwitchTheme {
            get {
                return ResourceManager.GetString("btnSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешки.
        /// </summary>
        internal static string CheckboxError {
            get {
                return ResourceManager.GetString("CheckboxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string CheckboxInfo {
            get {
                return ResourceManager.GetString("CheckboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успехи.
        /// </summary>
        internal static string CheckboxSuccess {
            get {
                return ResourceManager.GetString("CheckboxSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпълни всички.
        /// </summary>
        internal static string chkAllMacrosToExecute {
            get {
                return ResourceManager.GetString("chkAllMacrosToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завръщане на оригиналната позиция.
        /// </summary>
        internal static string chkReturnMouseToOriginal {
            get {
                return ResourceManager.GetString("chkReturnMouseToOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единичен клик,
        ///Двоен клик,
        ///Скролване,
        ///Десен бутон.
        /// </summary>
        internal static string cmbActionType {
            get {
                return ResourceManager.GetString("cmbActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторения.
        /// </summary>
        internal static string countAllMacroRepeatSliderLabel {
            get {
                return ResourceManager.GetString("countAllMacroRepeatSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторения.
        /// </summary>
        internal static string CountInputSliderLabel {
            get {
                return ResourceManager.GetString("CountInputSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текуща позиция: .
        /// </summary>
        internal static string CurrentPositionLabel {
            get {
                return ResourceManager.GetString("CurrentPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължителност (минути).
        /// </summary>
        internal static string DurationInputSliderLabel {
            get {
                return ResourceManager.GetString("DurationInputSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматичен Kликър.
        /// </summary>
        internal static string Form2 {
            get {
                return ResourceManager.GetString("Form2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Честота (секунди).
        /// </summary>
        internal static string FrequencyInputSliderLabel {
            get {
                return ResourceManager.GetString("FrequencyInputSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модални прозорци.
        /// </summary>
        internal static string groupBoxAllert {
            get {
                return ResourceManager.GetString("groupBoxAllert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цветови варианти.
        /// </summary>
        internal static string groupBoxCollors {
            get {
                return ResourceManager.GetString("groupBoxCollors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Езикови пакети.
        /// </summary>
        internal static string groupBoxLanguages {
            get {
                return ResourceManager.GetString("groupBoxLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string groupBoxTheme {
            get {
                return ResourceManager.GetString("groupBoxTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последен клик: .
        /// </summary>
        internal static string LastClickLabel {
            get {
                return ResourceManager.GetString("LastClickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спрени.
        /// </summary>
        internal static string materialLabelAllert {
            get {
                return ResourceManager.GetString("materialLabelAllert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тъмна.
        /// </summary>
        internal static string materialLabelTheme {
            get {
                return ResourceManager.GetString("materialLabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забавяне преди (мс).
        /// </summary>
        internal static string numericDelayBeforeSliderLabel {
            get {
                return ResourceManager.GetString("numericDelayBeforeSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забавяне след (мс).
        /// </summary>
        internal static string numericDelaySliderLabel {
            get {
                return ResourceManager.GetString("numericDelaySliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базов.
        /// </summary>
        internal static string RadioButtonBase {
            get {
                return ResourceManager.GetString("RadioButtonBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Син.
        /// </summary>
        internal static string RadioButtonBlue {
            get {
                return ResourceManager.GetString("RadioButtonBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зелен.
        /// </summary>
        internal static string RadioButtonGreen {
            get {
                return ResourceManager.GetString("RadioButtonGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Български.
        /// </summary>
        internal static string RadioButtonLanguageBG {
            get {
                return ResourceManager.GetString("RadioButtonLanguageBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немски.
        /// </summary>
        internal static string RadioButtonLanguageDE {
            get {
                return ResourceManager.GetString("RadioButtonLanguageDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английски.
        /// </summary>
        internal static string RadioButtonLanguageEN {
            get {
                return ResourceManager.GetString("RadioButtonLanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Френски.
        /// </summary>
        internal static string RadioButtonLanguageFR {
            get {
                return ResourceManager.GetString("RadioButtonLanguageFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оранжев.
        /// </summary>
        internal static string RadioButtonOrange {
            get {
                return ResourceManager.GetString("RadioButtonOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хронология  .  .  ..
        /// </summary>
        internal static string richTextBoxLogInfo {
            get {
                return ResourceManager.GetString("richTextBoxLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влизане.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай Макро.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвай.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string tabPage4 {
            get {
                return ResourceManager.GetString("tabPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете име за действието.
        /// </summary>
        internal static string textBoxActionNameHint {
            get {
                return ResourceManager.GetString("textBoxActionNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие 1.
        /// </summary>
        internal static string textBoxActionNameText {
            get {
                return ResourceManager.GetString("textBoxActionNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макро информация . . ..
        /// </summary>
        internal static string textBoxDisplayMacroInfo {
            get {
                return ResourceManager.GetString("textBoxDisplayMacroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете име за макрото.
        /// </summary>
        internal static string textBoxMacroNameHint {
            get {
                return ResourceManager.GetString("textBoxMacroNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макро 1.
        /// </summary>
        internal static string textBoxMacroNameText {
            get {
                return ResourceManager.GetString("textBoxMacroNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координат X.
        /// </summary>
        internal static string txtX {
            get {
                return ResourceManager.GetString("txtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координат Y.
        /// </summary>
        internal static string txtY {
            get {
                return ResourceManager.GetString("txtY", resourceCulture);
            }
        }
    }
}
